[project]
name = "odometry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "onnxruntime>=1.23.2",
    "onnxruntime-tools>=1.7.0",
    "opencv-python>=4.12.0.88",
    "tqdm>=4.67.1",
]
